---
abstract: 'Online payment processing via Ogone'
author:
  - 'Tim Esselens <tim.esselens@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-Ogone
requires:
  Business::OnlinePayment: 0
  Carp: 0
  Data::Dumper: 0
  Digest::SHA: 0
  MIME::Base64: 0
  Test::Most: 0
  XML::Simple: 0
  common::sense: 0
resources:
  homepage: https://github.com/timesselens/business-onlinepayment-ogone
  repository: https://github.com/timesselens/business-onlinepayment-ogone.git
version: 0.2.2.1
x_authority: cpan:ESSELENS
