---
abstract: 'Online payment processing via Ogone'
author:
  - 'Tim Esselens <tim.esselens@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-Ogone
requires:
  Business::OnlinePayment: 0
  Test::Most: 0
resources:
  homepage: http://github.com/timesselens/business-onlinepayment-ogone
  repository: http://github.com/timesselens/business-onlinepayment-ogone
version: 0.001
x_authority: cpan:ESSELENS
